Amend erroring data migration to associate entitues with reports
Error: https://rollbar.com/dxw/beis-roda/items/194/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification

The previous iteration of this data migration failed to run on production.
It appeared to run correctly on staging but either failed silently or did
not run because staging did not have any of the correct activity types.