Update Node to v16
This is the LTS version. We'd like to update to 18 as soon as we can as
v16 is going into maintenance mode in October this year.

Updating to 18 didn't work for us straight away, and gave us the
following error:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
        at Object.createHash (node:crypto:133:10)
            at module.exports
            (/app/node_modules/webpack/lib/util/createHash.js:135:53)
                at NormalModule._initBuildHash
                (/app/node_modules/webpack/lib/NormalModule.js:417:16)
                    at
                    /app/node_modules/webpack/lib/NormalModule.js:452:10
                        at
                        /app/node_modules/webpack/lib/NormalModule.js:323:13
                            at
                            /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
                                at
                                /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
                                    at context.callback
                                    (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
                                        at
                                        /app/node_modules/babel-loader/lib/index.js:59:103
                                        {
                                          opensslErrorStack: [
                                          'error:03000086:digital
                                          envelope
                                          routines::initialization
                                          error' ],
                                            library: 'digital envelope
                                            routines',
                                              reason: 'unsupported',
                                                code:
                                                'ERR_OSSL_EVP_UNSUPPORTED'
                                                }

```